binis_istasyon_id = 1135
inis_istasyon_id = 93
binis_istasyon_adi = "İZMİT YHT"
inis_istasyon_adi = "ESKİŞEHİR"
date = "2026-07-25"
istekli_saatler = []
email_address = os.environ["EMAIL_ADDRESS"]
email_password = os.environ["EMAIL_PASSWORD"]
destination_address = "receiver_mail@any_mail.com"
sleep_time = 300
